setwd('/Users/ZiangXiao/Developer/ComicPersuasion_withXinran/SU17Data')
pos_msg_data = read.csv("pos_msg_output.csv")
pos_var_data = read.csv("pos_var_output.csv")
pos_item_data = read.csv("pos_item_output.txt")
neg_msg_data = read.csv("neg_msg_output.csv")
neg_var_data = read.csv("neg_var_output.csv")
neg_item_data = read.csv("neg_item_output.txt")
all_item_data = read.csv("all_item_output.txt")
mean(pos_msg_data$M1)
mean(pos_msg_data$M2)
mean(pos_msg_data$M3)
mean(pos_msg_data$M4)
mean(pos_msg_data$M5)
pos_mod = lm(y ~ gesture+dist+shading , data = pos_item_data)
pos_mod_ = lm(y ~ gesture*dist*shading, data = pos_item_data)
summary(pos_mod)
summary(pos_mod_)
#Negative
mean(neg_msg_data$M1)
mean(neg_msg_data$M2)
mean(neg_msg_data$M3)
mean(neg_msg_data$M4)
mean(neg_msg_data$M5)
mean(neg_item_data$y)
neg_mod = lm(y ~ gesture+dist+shading , data = neg_item_data)
summary(neg_mod)
neg_mod_ = lm(y ~ gesture*dist*shading , data = neg_item_data)
summary(neg_mod_)
#All
mean(all_item_data$y)
all_mod = lm(y ~ gesture+dist+shading , data = all_item_data)
summary(all_mod)
all_mod_ = lm(y ~ gesture*dist*shading , data = all_item_data)
summary(all_mod_)

hist(neg_item_data$y)
