setwd('/Users/ZiangXiao/Developer/ComicPersuasion_withXinran/SU17Data')
pos_msg_data = read.csv("pos_msg_output.csv")
pos_var_data = read.csv("pos_var_output.csv")
pos_item_data = read.csv("pos_item_output.txt")
neg_msg_data = read.csv("neg_msg_output.csv")
neg_var_data = read.csv("neg_var_output.csv")
neg_item_data = read.csv("neg_item_output.txt")
mean(pos_msg_data$M1)
mean(pos_msg_data$M2)
mean(pos_msg_data$M3)
mean(pos_msg_data$M4)
mean(pos_msg_data$M5)
pos_mod = lm(y ~ gesture+dist+shading , data = pos_item_data)
summary(pos_mod)

#Negative
mean(neg_msg_data$M1)
mean(neg_msg_data$M2)
mean(neg_msg_data$M3)
mean(neg_msg_data$M4)
mean(neg_msg_data$M5)
neg_mod = lm(y ~ gesture+dist+shading , data = neg_item_data)
summary(neg_mod)
